import Link from "next/link";
import { fetchFeed, fetchRepoStats } from "@/lib/github";
import { getDispatch, getEnv } from "@/lib/kv";
import { getFacts } from "@/lib/facts";
import { Ticker } from "@/components/ticker";
import { StatGrid } from "@/components/stat-grid";
import { FeedCard } from "@/components/feed-card";
import { Seal } from "@/components/seal";
import { MermaidDiagram } from "@/components/mermaid-diagram";
import type { CuratedDispatch, FeedItem, RepoStats } from "@/lib/types";
import { GITEE_ENABLED } from "@/lib/i18n/config";

export const revalidate = 1800;

const FALLBACK_STATS: RepoStats = {
  stars: 0,
  forks: 0,
  openIssues: 0,
  openPulls: 0,
  contributors: 69,
  fetchedAt: new Date().toISOString(),
};

const FALLBACK_DISPATCH_EN: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "A local-first fiction workspace — quietly shipping",
  summary:
    "Writer is an open-source long-form fiction workspace that keeps story bibles, chapter drafts, audits, revisions, and continuity memory on disk. The dispatch below is regenerated by DeepSeek V4-Flash on a six-hour cron once the web draft is deployed.",
  highlights: [
    { title: "Read the install guide", href: "/install", tag: "shipped", blurb: "Per-OS instructions for Cargo, npm, source builds, and later release binaries." },
    { title: "Browse open issues", href: "https://github.com/luo-cccc/Writer/issues", tag: "opened", blurb: "Triaged on GitHub — start with anything labelled 'good first issue'." },
    { title: "Review the roadmap", href: "/roadmap", tag: "discussion", blurb: "What's confirmed, what's being weighed, what's been ruled out." },
  ],
  movers: [],
};

const FALLBACK_DISPATCH_ZH: CuratedDispatch = {
  generatedAt: new Date().toISOString(),
  headline: "一个本地优先的长篇小说工作台——安静迭代中",
  summary:
    "Writer 是一款开源长篇小说工作台，把故事圣经、章节草稿、审稿、修订和连续性记忆保存在本地文件中。Web 草稿部署后，以下「今日要闻」会由 DeepSeek V4-Flash 每六小时自动生成。",
  highlights: [
    { title: "阅读安装指南", href: "/zh/install", tag: "shipped", blurb: "覆盖 macOS、Linux、Windows，支持 Cargo、npm、源码构建及后续发布页二进制。" },
    { title: "浏览开放议题", href: "https://github.com/luo-cccc/Writer/issues", tag: "opened", blurb: "在 GitHub 上查看——从标记为 good first issue 的议题开始。" },
    { title: "查看路线图", href: "/zh/roadmap", tag: "discussion", blurb: "已确认、审议中、以及已排除的功能规划。" },
  ],
  movers: [],
};

export default async function HomePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  const isZh = locale === "zh";
  const env = await getEnv();
  const facts = await getFacts();

  let stats: RepoStats = FALLBACK_STATS;
  let feed: FeedItem[] = [];
  let dispatch: CuratedDispatch = isZh ? FALLBACK_DISPATCH_ZH : FALLBACK_DISPATCH_EN;

  try {
    [stats, feed] = await Promise.all([
      fetchRepoStats(env.GITHUB_TOKEN),
      fetchFeed(env.GITHUB_TOKEN, 12),
    ]);
  } catch (e) {
    console.error("github fetch failed", e);
  }

  try {
    const cached = await getDispatch();
    if (cached) dispatch = cached;
  } catch {
    /* keep fallback */
  }

  return (
    <>
      <Ticker items={feed} />

      {/* HERO */}
      <section className="relative overflow-hidden">
        <div className="margin-glyph right-[-2rem] top-[2rem] hidden lg:block">深</div>

        <div className="mx-auto max-w-[1400px] px-4 sm:px-6 pt-10 sm:pt-14 pb-12 grid lg:grid-cols-12 gap-10">
          <div className="lg:col-span-8">
            <div className="flex items-center gap-2 sm:gap-3 mb-6 flex-wrap">
              <span className="pill pill-hot">v4 · 1M context</span>
              <span className="pill pill-ghost">MIT licensed</span>
            </div>

            <h1 className="font-display tracking-crisp">
              {isZh
                ? "一个住在终端里的长篇小说工作台。"
                : "A long-form fiction workspace that lives in your terminal."}
            </h1>

            <p className="mt-6 text-lg text-ink-soft leading-relaxed max-w-2xl">
              <span className="font-cjk text-indigo font-semibold">深度求索</span> ·{" "}
              <strong>Writer</strong>{" "}
              {isZh
                ? "是一款基于 DeepSeek V4 系列的本地优先小说创作工作台。它创建书籍工程、生成章节、审稿修订，并维护连续性记忆。"
                : "is a local-first fiction workspace built on the DeepSeek V4 family. It creates book projects, drafts chapters, audits revisions, and maintains continuity memory."}
            </p>

            <div className="mt-8 flex flex-wrap items-stretch sm:items-center gap-3">
              <Link
                href={isZh ? "/zh/install" : "/install"}
                className="flex-1 sm:flex-none text-center px-5 py-3 bg-ink text-paper font-mono text-sm uppercase tracking-wider hover:bg-indigo transition-colors"
              >
                {isZh ? "30 秒完成安装 →" : "Install in 30 seconds →"}
              </Link>
              <Link
                href="https://github.com/luo-cccc/Writer"
                className="flex-1 sm:flex-none text-center px-5 py-3 hairline-t hairline-b hairline-l hairline-r font-mono text-sm uppercase tracking-wider hover:bg-paper-deep transition-colors"
              >
                ★ Star on GitHub
              </Link>
              <Link
                href={isZh ? "/zh/docs" : "/docs"}
                className="px-5 py-3 font-mono text-sm uppercase tracking-wider text-ink-mute hover:text-indigo transition-colors"
              >
                {isZh ? "阅读文档" : "Read the docs"}
              </Link>
              <Link
                href="https://github.com/luo-cccc/Writer"
                className="px-5 py-3 font-mono text-sm uppercase tracking-wider text-ink-mute hover:text-indigo transition-colors"
              >
                {isZh ? "支持项目 ↗" : "Support ↗"}
              </Link>
            </div>

            {/* Trust signals */}
            <div className="mt-6 flex items-center gap-4 text-xs font-mono text-ink-mute flex-wrap">
              {isZh ? (
                <span>独立维护者 luo-cccc{GITEE_ENABLED && <> · <a href="https://gitee.com/luo-cccc/Writer" className="text-indigo hover:underline">Gitee 镜像</a></>}</span>
              ) : (
                <span>Maintained by luo-cccc</span>
              )}
            </div>
          </div>

          {/* hero side: cargo install card */}
          <div className="lg:col-span-4">
            <div className="hairline-t hairline-b hairline-l hairline-r bg-paper p-5 relative">
              <div className="absolute -top-3 left-4 bg-paper px-2 eyebrow">
                {isZh ? "最快安装 · 一行搞定" : "quickest path · 一行安装"}
              </div>
              <pre className="code-block mt-2">
                {isZh ? (
                  <>
                    <span className="comment"># macOS / Linux — Cargo</span>{"\n"}
                    <span className="prompt">$</span> cargo install deepseek-tui-cli --locked{"\n"}
                    <span className="prompt">$</span> deepseek{"\n"}
                    <br />
                    <span className="comment"># 或通过 npm 安装</span>{"\n"}
                    <span className="prompt">$</span> npm i -g deepseek-tui{"\n"}
                    <br />
                    <span className="comment"># 首次运行会自动创建 <span className="key">~/.deepseek/</span></span>{"\n"}
                    <br />
                    <span className="comment"># 国内镜像</span>{"\n"}
                    <span className="prompt">$</span> npm config set registry https://registry.npmmirror.com{"\n"}
                    <span className="prompt">$</span> npm i -g deepseek-tui
                  </>
                ) : (
                  <>
                    <span className="comment"># macOS / Linux — Cargo</span>{"\n"}
                    <span className="prompt">$</span> cargo install deepseek-tui-cli --locked{"\n"}
                    <span className="prompt">$</span> deepseek{"\n"}
                    <br />
                    <span className="comment"># or via npm wrapper</span>{"\n"}
                    <span className="prompt">$</span> npm i -g deepseek-tui{"\n"}
                    <br />
                    <span className="comment"># first run sets up <span className="key">~/.deepseek/</span></span>
                  </>
                )}
              </pre>
              <div className="mt-3 flex items-center justify-between text-[0.7rem] font-mono text-ink-mute">
                <span>{isZh ? `需要 Rust 1.88+ 或 Node ${facts.nodeEngines ?? ">=18"}` : `requires Rust 1.88+ or Node ${facts.nodeEngines ?? ">=18"}`}</span>
                <Link href={isZh ? "/zh/install" : "/install"} className="text-indigo hover:underline">{isZh ? "其他系统 →" : "other OSes →"}</Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      <StatGrid stats={stats} />

      {/* TODAY'S DISPATCH */}
      <section className="mx-auto max-w-[1400px] px-6 py-16">
        <div className="flex items-end justify-between mb-6 hairline-b pb-4">
          <div>
            <div className="eyebrow mb-2">{isZh ? "今日要闻" : "Today's Dispatch · 今日要闻"}</div>
            <h2 className="font-display tabular text-ink-mute font-mono text-base">
              {new Date(dispatch.generatedAt).toISOString().slice(0, 10)}
            </h2>
          </div>
          <div className="text-right">
            <div className="eyebrow">{isZh ? "由 … 编辑" : "Curated by"}</div>
            <div className="font-mono text-sm">DeepSeek V4-Flash · 6h cron</div>
          </div>
        </div>

        <div className="grid lg:grid-cols-12 gap-10">
          {/* editorial */}
          <div className="lg:col-span-7">
            <article className="space-y-5">
              <h3 className="font-display text-3xl leading-tight">
                {dispatch.headline}
              </h3>
              <p className={`${isZh ? "text-ink-soft leading-[1.9] tracking-wide text-[1.02rem]" : "text-ink-soft leading-relaxed text-[1.02rem]"}`}>
                {dispatch.summary}
              </p>

              <div className="hairline-t pt-5">
                <div className="eyebrow mb-3">{isZh ? "要点" : "Highlights · 要点"}</div>
                <ul className="divide-y divide-paper-line/40 hairline-t hairline-b">
                  {dispatch.highlights.map((h, i) => (
                    <li key={i} className="py-3 flex items-start gap-4">
                      <span className="font-mono text-[0.7rem] text-indigo uppercase tracking-widest pt-1 w-20 shrink-0">
                        {h.tag}
                      </span>
                      <div className="flex-1">
                        <Link href={h.href} className="body-link font-display text-lg leading-snug">
                          {h.title}
                        </Link>
                        <p className={`text-sm text-ink-soft mt-1 ${isZh ? "leading-[1.8]" : ""}`}>{h.blurb}</p>
                      </div>
                    </li>
                  ))}
                </ul>
              </div>

              {dispatch.movers.length > 0 && (
                <div className="pt-2">
                  <div className="eyebrow mb-3">{isZh ? "进展" : "Movers · 进展"}</div>
                  <ul className="space-y-2">
                    {dispatch.movers.map((m) => (
                      <li key={m.number} className="flex items-baseline gap-3 text-sm">
                        <span className="font-mono text-indigo tabular">#{m.number}</span>
                        <Link href={m.href} className="font-medium hover:text-indigo">{m.title}</Link>
                        <span className="text-ink-mute">— {m.reason}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </article>
          </div>

          {/* recent activity column */}
          <aside className="lg:col-span-5">
            <div className="hairline-t hairline-b hairline-l hairline-r bg-paper">
              <div className="bg-ink text-paper px-4 py-2 flex items-center justify-between">
                <div className="font-cjk text-sm tracking-wider">{isZh ? "最新活动" : "最新活动 · Recent activity"}</div>
                <Link href={isZh ? "/zh/feed" : "/feed"} className="font-mono text-[0.7rem] uppercase tracking-wider hover:text-indigo">
                  {isZh ? "全部 →" : "All →"}
                </Link>
              </div>
              <div className="px-4">
                {feed.slice(0, 5).map((item) => (
                  <FeedCard key={item.url} item={item} />
                ))}
                {feed.length === 0 && (
                  <div className="py-8 text-center text-sm text-ink-mute font-mono">
                    {isZh ? "暂无数据 · feed not loaded" : "feed not yet loaded · 暂无数据"}
                  </div>
                )}
              </div>
            </div>
          </aside>
        </div>
      </section>

      {/* WHAT IT IS — 3 column */}
      <section className="bg-paper-deep hairline-t hairline-b">
        <div className="mx-auto max-w-[1400px] px-6 py-16">
          <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
            <Seal char="是" />
            <h2 className="font-display">
              {isZh ? "它到底是什么" : "What it actually is"}
            </h2>
          </div>

          <div className="grid md:grid-cols-3 gap-0 col-rule hairline-t hairline-b">
            {isZh ? (
              <>
                <div className="p-6">
                  <div className="eyebrow mb-3">01 · 小说工程</div>
                  <h3 className="font-display text-xl mb-3">书籍工程，不是聊天框</h3>
                  <p className="text-sm text-ink-soft leading-[1.9]">
                    `deepseek init` 创建本地书籍结构，章节、审稿、修订和记忆都落在可追踪文件中。
                  </p>
                </div>
                <div className="p-6">
                  <div className="eyebrow mb-3">02 · 连续性记忆</div>
                  <h3 className="font-display text-xl mb-3">记住事实、伏笔和人物边界</h3>
                  <p className="text-sm text-ink-soft leading-[1.9]">
                    长篇记忆图按章节、角色、地点、物件、承诺和摘要组织上下文，避免后期噪声淹没关键事实。
                  </p>
                </div>
                <div className="p-6">
                  <div className="eyebrow mb-3">03 · 模型自由</div>
                  <h3 className="font-display text-xl mb-3">默认 {facts.defaultModel ?? "DeepSeek V4"}</h3>
                  <p className="text-sm text-ink-soft leading-[1.9]">
                    内建 {facts.providers.length} 个提供商。可固定模型做基准，也可用 auto 在章节创作和审稿间调度。
                  </p>
                </div>
              </>
            ) : (
              <>
                <div className="p-6">
                  <div className="eyebrow mb-3">01 · fiction project</div>
                  <h3 className="font-display text-xl mb-3">A book workspace, not a chat box</h3>
                  <p className="text-sm text-ink-soft leading-relaxed">
                    `deepseek init` creates a local book structure. Chapters, audits, revisions, and memory stay in trackable files.
                  </p>
                </div>
                <div className="p-6">
                  <div className="eyebrow mb-3">02 · continuity memory</div>
                  <h3 className="font-display text-xl mb-3">Facts, promises, and knowledge boundaries</h3>
                  <p className="text-sm text-ink-soft leading-relaxed">
                    The memory graph keeps chapters, characters, locations, objects, promises, and summaries queryable without flattening the whole book.
                  </p>
                </div>
                <div className="p-6">
                  <div className="eyebrow mb-3">03 · 模型自由</div>
                  <h3 className="font-display text-xl mb-3">{facts.defaultModel ?? "DeepSeek V4"} by default</h3>
                  <p className="text-sm text-ink-soft leading-relaxed">
                    {facts.providers.length} built-in providers. Pin models for benchmarks or let auto routing choose between drafting and review.
                  </p>
                </div>
              </>
            )}
          </div>
        </div>
      </section>

      {/* HOW IT WORKS — mermaid diagram (replaces brittle ASCII art that
           misaligned under CJK monospace, per dhh's note) */}
      <section className="mx-auto max-w-[1400px] px-6 py-16">
        <div className="flex items-baseline gap-4 mb-8 hairline-b pb-4">
          <Seal char="作" />
          <h2 className="font-display">
            {isZh ? "运作方式" : "How it works"}
          </h2>
        </div>

        <div className="hairline-t hairline-b hairline-l hairline-r bg-paper p-4 sm:p-8">
          <MermaidDiagram
            label={isZh ? "Writer 运作方式示意图" : "Writer architecture diagram"}
            chart={
              isZh
                ? `flowchart TD
    A["用户输入<br/>(TUI · ratatui)"] -->|Op channel| B["Engine<br/>turn loop + tools"]
    B -->|HTTPS / SSE| C["DeepSeek API<br/>V4 family"]
    C -->|stream events| B
    B -->|tool call| T["read_file · edit_file · grep<br/>apply_patch · exec_shell<br/>mcp_&lt;server&gt;_&lt;tool&gt;"]
    T -->|approval Y/N| P["审批对话框<br/>approval dialog"]
    P --> B
    T -->|exec| S["沙箱<br/>seatbelt · landlock · win32"]
    classDef accent fill:#e9eefe,stroke:#0e0e10,stroke-width:1px;
    classDef api fill:#0e0e10,stroke:#0e0e10,color:#ffffff;
    class C api;
    class T,P,S accent;`
                : `flowchart TD
    A["You type<br/>(TUI · ratatui)"] -->|Op channel| B["Engine<br/>turn loop + tools"]
    B -->|HTTPS / SSE| C["DeepSeek API<br/>V4 family"]
    C -->|stream events| B
    B -->|tool call| T["read_file · edit_file · grep<br/>apply_patch · exec_shell<br/>mcp_&lt;server&gt;_&lt;tool&gt;"]
    T -->|approval Y/N| P["Approval<br/>dialog"]
    P --> B
    T -->|exec| S["Sandbox<br/>seatbelt · landlock · win32"]
    classDef accent fill:#e9eefe,stroke:#0e0e10,stroke-width:1px;
    classDef api fill:#0e0e10,stroke:#0e0e10,color:#ffffff;
    class C api;
    class T,P,S accent;`
            }
          />
        </div>

        <p className="mt-3 text-xs font-mono text-ink-mute">
          {isZh
            ? "示意图使用 Mermaid 标准格式渲染。"
            : "Rendered with Mermaid standard syntax."}
        </p>
      </section>

      {/* JOIN IN */}
      <section className="bg-ink text-paper">
        <div className="mx-auto max-w-[1400px] px-6 py-16 grid lg:grid-cols-12 gap-10">
          <div className="lg:col-span-5">
            <div className="eyebrow text-paper-deep/70 mb-3">{isZh ? "加入" : "Join in"}</div>
            <h2 className="font-display text-paper text-4xl leading-tight">
              {isZh ? "这是一个小项目。你的每个补丁都很重要。" : "This is a small project. Your patch matters."}
            </h2>
            <p className={`mt-5 text-paper-deep/80 ${isZh ? "leading-[1.9]" : "leading-relaxed"}`}>
              {isZh
                ? "无 CLA，无赞助商锁定。维护者亲自阅读每一条内容——通常在一天内回复。议题在公开环境下分类。版本从 main 分支发布。"
                : "No CLA. No sponsor lockouts. The maintainer reads everything personally — usually within a day. Issues triaged in the open. Releases cut from main."}
            </p>
          </div>

          <div className="lg:col-span-7 grid sm:grid-cols-3 gap-px bg-paper/15">
            {(isZh
              ? [
                  { t: "提交议题", cn: "提 Bug 或功能建议", d: "Bug 报告、功能需求，或一个好问题。", href: "https://github.com/luo-cccc/Writer/issues/new/choose" },
                  { t: "提交 PR", cn: "贡献代码", d: "Fork、分支、conventional commit、提交 PR。", href: "/zh/contribute" },
                  { t: "发起讨论", cn: "参与设计", d: "路线图、架构设计、任何非 Bug 的话题。", href: "https://github.com/luo-cccc/Writer/discussions" },
                ]
              : [
                  { t: "Open an issue", cn: "提议题", d: "Bug, feature, or just a sharp question.", href: "https://github.com/luo-cccc/Writer/issues/new/choose" },
                  { t: "Send a PR", cn: "提交合并", d: "Fork, branch, conventional commit, open PR.", href: "/contribute" },
                  { t: "Start a discussion", cn: "发起讨论", d: "Roadmap, design, anything that's not a bug.", href: "https://github.com/luo-cccc/Writer/discussions" },
                ]
            ).map((c) => (
              <Link
                key={c.t}
                href={c.href}
                className="bg-ink p-6 hover:bg-indigo group transition-colors"
              >
                <div className="font-cjk text-sm text-indigo group-hover:text-paper transition-colors mb-2">
                  {c.cn}
                </div>
                <div className="font-display text-xl mb-2">{c.t}</div>
                <div className="text-sm text-paper-deep/80 group-hover:text-paper">{c.d}</div>
                <div className="mt-4 font-mono text-[0.7rem] uppercase tracking-widest text-paper-deep/60 group-hover:text-paper">
                  {isZh ? "前往 →" : "Go →"}
                </div>
              </Link>
            ))}
          </div>
        </div>
      </section>
    </>
  );
}
